name: moneymemos
description: "MoneyMemos - precise information about stcok"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.0.0
  get_it: ^8.0.3
  injectable: ^2.5.0
  dio: ^5.8.0+1
  retrofit: ^4.4.2
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  dartz: ^0.10.1
  equatable: ^2.0.7
  cached_network_image: ^3.4.1
  google_sign_in: ^7.1.1
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  firebase_messaging: ^16.0.0
  firebase_crashlytics: ^5.0.0
  firebase_analytics: ^12.0.0
  firebase_performance: ^0.11.0
  firebase_performance_dio: ^0.7.1
  flutter_local_notifications: ^19.0.0
  firebase_remote_config: ^6.0.0
  network_monitor_cp: ^0.0.7
  logger: ^2.5.0
  go_router: ^16.1.0
  shared_preferences: ^2.5.3
  synchronized: ^3.3.0+3
  google_fonts: ^6.2.1
  flutter_svg: ^2.1.0
  flutter_cache_manager: ^3.4.1
  shimmer: ^3.0.0
  




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.6.0
  injectable_generator: ^2.8.1
  freezed: ^3.2.0
  json_serializable: ^6.10.0
  retrofit_generator: ^10.0.1

flutter:

  uses-material-design: true
  assets:
    - assets/svg/